# NumPy & Arrays

NumPy (Numerical Python) is the foundation of scientific computing in Python. It provides fast, memory-efficient N-dimensional arrays and powerful operations.

Key benefits over Python lists:
- Vectorized operations (no loops needed!)
- Faster computation (written in C)
- Rich library of mathematical functions


### What is NumPy?

**NumPy** (Numerical Python) is the fundamental package for scientific computing in Python. It provides:
- Multi-dimensional array objects (`ndarray`)
- Fast vectorized operations (no Python loops needed)
- Linear algebra, random number generation, and statistical functions
- Broadcasting — operations on arrays of different shapes

NumPy is the foundation that pandas, scikit-learn, and many other libraries are built upon.


## Getting Started

Import NumPy with the standard alias `np`:


In [15]:
# Import NumPy with its standard alias 'np'
import numpy as np



In [14]:
# ndmin=2 forces the array to have at least 2 dimensions
# Create a 2D array from a Python list
arr = np.array([12,3,4,5],ndmin=2)

## Why NumPy? Performance Comparison

NumPy arrays are significantly faster than Python lists for numerical operations because they use compiled C code and contiguous memory.


# NumPy import — needed before any NumPy operations
### Why NumPy is Faster Than Python Lists

| Feature | Python List | NumPy Array |
|---------|-------------|-------------|
| Memory | Stores objects (pointers) | Stores values in contiguous memory |
| Operations | Must loop element-by-element | Vectorized (C-level loops) |
| Data types | Mixed types allowed | Homogeneous (all same type) |
| Speed | Slow for numerical data | 10-100x faster |

NumPy achieves this by using **fixed-type data** stored in a **contiguous memory block**, enabling highly optimized C and Fortran code to operate on the data.


In [15]:
import numpy as np



In [14]:
# ndmin=2 creates a 2D array even from a 1D list
arr = np.array([12,3,4,5],ndmin=2)

In [ ]:
# .shape returns a tuple of dimension sizes
# .ndim prints the number of dimensions
print(arr)
print(arr.ndim)
print(arr.shape)

[[12  3  4  5]]
2
(1, 4)


## Multi-dimensional Arrays & Reshaping

- `.reshape(rows, cols)` — change shape (total elements must match)
- `ndmin=N` — create with minimum N dimensions
- Use nested lists for 2D, 3D, 4D arrays


In [19]:
# .reshape(3,3) rearranges 9 elements into a 3×3 matrix
arr = np.array([1,2,3,4,5,6,7,8,9])
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Outer list has 2 elements, each is 2×1
# 3D array with shape (2, 2, 1)
arr2 = np.array([[[1],[1]],[[1],[1]]])

In [33]:
# Examine the properties of a 3D array
print(arr2)
print(arr2.shape)
print("dimesnerions are: ,",arr2.ndim)

[[[1]
  [1]]

 [[1]
  [1]]]
(2, 2, 1)
dimesnerions are: , 3


In [7]:
# Create a simple 1D array from a list
arr =np.array([1,2,3,4])

In [8]:
# In Jupyter, the last expression is auto-displayed
arr

array([1, 2, 3, 4])

Numpy Again


In [5]:
# Re-import NumPy for timing demo
# time module for performance comparison
import time
import numpy as np

# 1. Setup data size (10 million items)
DATA_SIZE = 10_000_000

# Initialize a standard Python list and a NumPy array
py_list = list(range(DATA_SIZE))
np_array = np.arange(DATA_SIZE)

print(f"Benchmarking operations over {DATA_SIZE:,} elements...\n")

# --- TEST 1: SUMMATION ---
# Measure Python list sum
start_time = time.time()
list_sum = sum(py_list)
list_sum_time = time.time() - start_time

# Measure NumPy array sum
start_time = time.time()
array_sum = np.sum(np_array)
array_sum_time = time.time() - start_time

print("### Test 1: Summing Elements ###")
print(f"Python List time: {list_sum_time:.5f} seconds")
print(f"NumPy Array time: {array_sum_time:.5f} seconds")
print(f"👉 NumPy is {list_sum_time / array_sum_time:.1f}x faster\n")


# --- TEST 2: ELEMENT-WISE MULTIPLICATION ---
# Measure Python list multiplication (requires a loop/list comprehension)
start_time = time.time()
list_mult = [x * 2 for x in py_list]
list_mult_time = time.time() - start_time

# Measure NumPy array multiplication (uses optimized vectorization)
start_time = time.time()
array_mult = np_array * 2
array_mult_time = time.time() - start_time

print("### Test 2: Multiplying Elements by 2 ###")
print(f"Python List time: {list_mult_time:.5f} seconds")
print(f"NumPy Array time: {array_mult_time:.5f} seconds")
print(f"👉 NumPy is {list_mult_time / array_mult_time:.1f}x faster\n")


Benchmarking operations over 10,000,000 elements...

### Test 1: Summing Elements ###
Python List time: 0.28637 seconds
NumPy Array time: 0.04044 seconds
👉 NumPy is 7.1x faster

### Test 2: Multiplying Elements by 2 ###
Python List time: 0.43839 seconds
NumPy Array time: 0.01956 seconds
👉 NumPy is 22.4x faster



## Creating NumPy Arrays

Create arrays from Python lists. NumPy also provides utility functions:
- `np.zeros(shape)` — array of zeros
- `np.ones(shape)` — array of ones
- `np.arange(start, stop, step)` — like `range()` but returns array
- `np.linspace(start, stop, n)` — n evenly spaced numbers
- `np.full(shape, value)` — array filled with a value


In [ ]:
# Compare Python list vs NumPy array creation
# Reshape is a view (not a copy) — modifying affects original!
original = np.array([1, 2, 3, 4, 5, 6])
reshaped = original.reshape(2, 3)
print("Original:", original)
print("Reshaped (2,3):\n", reshaped)

# Modifying the reshaped view also changes the original
reshaped[0, 0] = 99
print("After modifying view:")
print("Reshaped:\n", reshaped)
print("Original:", original)  # Changed!


In [ ]:
# Identity matrix
identity = np.eye(4)
print("Eye (4x4 identity):\n", identity)

# Array of ones
ones_arr = np.ones((2, 3))
print("\nOnes (2x3):\n", ones_arr)

# Full array with constant
full_arr = np.full((2, 3), 42)
print("\nFull (2x3 filled with 42):\n", full_arr)


In [ ]:
# arange — like range() but returns an array
step_arr = np.arange(0, 1, 0.1)
print("arange(0, 1, 0.1):", step_arr)

# linspace — evenly spaced numbers over an interval
evenly = np.linspace(0, 1, 5)  # 5 numbers between 0 and 1
print("linspace(0, 1, 5):", evenly)


## Creating NumPy Arrays

NumPy provides several utility functions to create arrays:

| Function | Description |
|----------|-------------|
| `np.array([...])` | Create from list/tuple |
| `np.zeros(shape)` | All zeros |
| `np.ones(shape)` | All ones |
| `np.full(shape, val)` | Fill with constant |
| `np.arange(start, stop, step)` | Like `range()` but returns array |
| `np.linspace(start, stop, n)` | `n` evenly spaced points |
| `np.eye(N)` | Identity matrix (N×N) |
| `np.random.rand(shape)` | Random uniform [0, 1) |


In [7]:
li = [1,2,3,4,5]
arr = np.array([1,2,3,4,5])

In [8]:
# Each element multiplication happens in Python (slow)
# Python list requires explicit loops
for i in li:
    print(i*2)

2
4
6
8
10


In [16]:
# NumPy array displayed without loop
arr

array([1, 2, 3, 4, 5])

## Array Properties

- `.ndim` — number of dimensions
- `.shape` — tuple of dimensions (rows, cols, ...)
- `.size` — total number of elements
- `.dtype` — data type of elements


# .ndim tells us how many dimensions the array has
## Array Properties

Every `ndarray` has these key attributes:

| Attribute  | Description |
|------------|-------------|
| `.ndim`    | Number of dimensions (1D, 2D, 3D, ...) |
| `.shape`   | Tuple of dimension sizes |
| `.size`    | Total number of elements |
| `.dtype`   | Data type of elements (`int32`, `float64`, etc.) |
| `.itemsize`| Bytes per element |


In [14]:
arr.ndim

1

In [ ]:
# .size = total elements, .dtype = element type
print("Size:", arr.size)     # total elements
print("Dtype:", arr.dtype)   # int32 or int64 etc.
print("itemsize:", arr.itemsize, "bytes")  # bytes per element


In [15]:
# .shape = tuple of dimension sizes
arr.shape

(5,)

In [ ]:
# Shape is specified as a tuple (rows, cols)
# np.zeros creates an array filled with 0.0
# Array creation utility functions
zeros_arr = np.zeros((3, 4))
print("Zeros:\n", zeros_arr)

ones_arr = np.ones((2, 3))
print("Ones:\n", ones_arr)

range_arr = np.arange(0, 20, 2)
print("Arange:", range_arr)  # [ 0  2  4  6  8 10 12 14 16 18]

linspace_arr = np.linspace(0, 1, 5)
print("Linspace:", linspace_arr)  # [0.   0.25 0.5  0.75 1.  ]


In [25]:
# ndmin=4 forces a 4D array even from flat input
arr2D = np.array([1,2,3,4],ndmin=4)

In [26]:
# Higher-dimensional arrays can be hard to visualize
print(arr2D)
print(arr2D.shape)

[[[[1 2 3 4]]]]
(1, 1, 1, 4)


In [28]:
# Creating a 2D array from a list of lists
arrMultiDimension = np.array([[1,2,3,4],[5,6,7,8]])

In [30]:
# Shape reveals the dimensions (2 rows, 4 columns)
arrMultiDimension.shape

(2, 4)

In [34]:
# Creating a 3D array — shape (2, 3, 4)
arr3D =np.array([[[1,2,3,4],[5,6,7,8],[5,6,7,8]],[[1,2,3,4],[5,6,7,8],[5,6,7,8]]])

In [ ]:
# Indexing into a 3D array
arr3D
"""
array([[7, 8],
        [7, 8]],

        [7, 8],
        [7, 8]]])
"""

array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8],
        [5, 6, 7, 8]]])

In [38]:
# Another 2D array for slicing demonstrations
arr2D = np.array([[1,2,3,4],[5,6,7,8]])

In [39]:
# Display the 2D array
arr2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Indexing & Slicing

Access array elements with indices and slices:
- 1D: `arr[start:end:step]`
- 2D: `arr[row_start:row_end, col_start:col_end]`
- 3D: `arr[depth_start:depth_end, row_start:row_end, col_start:col_end]`


# 2D slicing: select all rows, columns 1 and 2
## Indexing & Slicing

NumPy slicing works like Python list slicing — but extended to multiple dimensions!

```python
arr2D[row_start:row_end, col_start:col_end]
```

**Rules:**
- Omitted start = beginning, omitted end = end
- Negative indices count from the end
- You can mix integers (single element) and slices (sub-array)


In [51]:
arr2D[:,1:3]

array([[2, 3],
       [6, 7]])

In [56]:
# Re-create 3D array for demonstration
arr3D =np.array([[[1,2,3,4],[5,6,7,8],[5,6,7,8]],[[1,2,3,4],[5,6,7,8],[5,6,7,8]]])
arr3D

array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8],
        [5, 6, 7, 8]]])

In [55]:
# Slice 3D array: rows 0+, inner dimension 1+, columns 2+
arr3D[0:,1:,2:]

array([[[7, 8],
        [7, 8]],

       [[7, 8],
        [7, 8]]])

In [57]:
# Create array with values 0 through 99
Arr = np.array(range(0,100))

In [58]:
# Display the sequential array
Arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [61]:
# This is slow for large datasets — NumPy can do this faster!
# Manual filtering using Python loops
evenList = []
oddList = []
for i in Arr:
    if i%2 == 0:
        evenList.append(i)
    else:
        oddList.append(i)

In [65]:
# Convert filtered lists to NumPy arrays
evenArray = np.array(evenList)
oddArrat = np.array(oddList)

In [67]:
# Display the even and odd arrays
evenArray
oddArrat

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

## Filtering & Boolean Indexing

Use boolean conditions to filter arrays. The condition returns a boolean mask.
```python
arr[arr > 50]  # all elements greater than 50
```


In [ ]:
# Boolean indexing: condition is applied element-wise
# Sorting arrays
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
sorted_arr = np.sort(unsorted)
print("Sorted:", sorted_arr)

# Unique values (sorted, duplicates removed)
unique_vals = np.unique(unsorted)
print("Unique:", unique_vals)


In [ ]:
# np.clip — clamp values between a minimum and maximum
data = np.array([1, 5, 10, 15, 20, 25])
clipped = np.clip(data, 5, 20)
print("Original:", data)
print("Clipped [5, 20]:", clipped)


In [ ]:
# np.where — conditional selection (like if-else for arrays)
arr = np.array([10, 25, 30, 45, 50, 65])

# Where condition is True, pick from x, else pick from y
result = np.where(arr > 40, arr * 2, arr / 2)
print("Original:", arr)
print("Where (>40):", result)


## Boolean Indexing (Filtering)

One of NumPy's most powerful features: apply a condition directly to an array to get a boolean mask, then use that mask to select elements.

```python
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3        # array([False, False, False, True, True])
print(arr[mask])      # [4, 5]

# One-liner:
print(arr[arr > 3])   # [4, 5]
```

You can combine conditions with `&` (and), `|` (or), `~` (not).


In [71]:
evenArray = Arr[Arr%2==0]
oddArray = Arr[Arr%2!=0]

In [73]:
# NumPy's boolean filtering is faster and more concise
print(evenArray)
print(oddArray)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [76]:
# Arrays are mutable — elements can be changed by index
evenArray[1]=5 

## Array Operations & Broadcasting

NumPy performs element-wise operations without loops (vectorization). Broadcasting automatically expands smaller arrays to match larger ones.


In [ ]:
# Each element is added element-wise
# Vectorized operations — no explicit loop needed!
# Concatenating arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

v_stack = np.vstack((a, b))  # vertical stack (add rows)
print("Vstack:\n", v_stack)

c = np.array([[5], [6]])
h_stack = np.hstack((a, c))  # horizontal stack (add columns)
print("\nHstack:\n", h_stack)


In [ ]:
# Dot product (matrix multiplication)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

dot_product = np.dot(A, B)   # matrix multiplication
print("A dot B:\n", dot_product)

# @ operator — same as np.dot() (Python 3.5+)
print("\nA @ B:\n", A @ B)

# Element-wise multiplication (not matrix multiplication!)
print("\nA * B (element-wise):\n", A * B)


In [ ]:
# Broadcasting example: add a scalar to an array
arr = np.array([1, 2, 3, 4])
print("arr + 10:", arr + 10)   # [11, 12, 13, 14]

# Broadcasting: add a 1D array to a 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6]])
row = np.array([10, 20, 30])
print("\nMatrix + row:\n", matrix + row)  # row broadcasts to match matrix

# Broadcasting: different shapes
A = np.array([[1], [2], [3]])  # shape (3, 1)
B = np.array([10, 20, 30])    # shape (3,)
print("\nA (3,1) + B (3,):\n", A + B)  # result (3, 3)


## Broadcasting Rules

**Broadcasting** lets NumPy perform operations on arrays of different shapes. NumPy automatically "stretches" the smaller array to match the larger one.

**Rules:**
1. If arrays have different dimensions, prepend 1s to the smaller shape
2. Arrays are compatible if dimensions are equal or one is 1
3. The result takes the larger shape

**Examples:**
- `(3, 4) + (4,)` → `(3, 4) + (1, 4)` → `(3, 4)` ✓
- `(3, 4) + (3,)` → `(3, 4) + (1, 3)` → ✗ (different trailing dims)
- `(3, 1) + (1, 4)` → `(3, 4)` ✓ (both dimensions broadcast)


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(a + b)    # [11 22 33 44] — element-wise addition
print(a * b)    # [ 10  40  90 160] — element-wise multiplication
print(a ** 2)   # [ 1  4  9 16] — square each element
print(a * 10)   # [10 20 30 40] — broadcasting: scalar × array


In [78]:
# Student marks for grading demonstration
studentMarks = np.array([25 , 50, 80 , 90 ,10 , 33])
# 80 > A
# 80 < B
# 50 < C
# 33 <= F 

In [94]:
# Manual grading with Python loop
gradeList = []
for i in studentMarks:
    if i >=80:
        gradeList.append("A")
    elif i<80 and i >= 50:
        gradeList.append("B")
    elif i>= 33 and i < 50:
        gradeList.append("C")
    elif i<=33:
        gradeList.append("F")
gradeArray = np.array(gradeList)


In [95]:
# Display original marks and computed grades
print(studentMarks)
print(gradeArray)

[25 50 80 90 10 33]
['F' 'B' 'A' 'A' 'F' 'C']


In [93]:
# Much faster than a Python for loop!
# Vectorized grading using np.select
studentMarks = np.array([25 , 50, 80 , 90 ,10 , 33])

condition = [(studentMarks >=80),(studentMarks >=50),(studentMarks>=33)]
grade = ["A","B","C"]
gradeArray = np.select(condition,grade,default="F")
print(gradeArray)

['F' 'B' 'A' 'A' 'F' 'C']


In [ ]:
# Empty cell placeholder


## Statistical Functions

NumPy provides many statistical functions that operate on entire arrays:
- `np.mean(arr)`, `np.median(arr)`, `np.std(arr)`
- `np.min(arr)`, `np.max(arr)`, `np.sum(arr)`
- Use `axis=0` for columns, `axis=1` for rows


In [ ]:
# Statistical summary of a dataset
# Statistical functions with axis parameter
data_2d = np.array([[10, 20, 30], [40, 50, 60]])

print("Matrix:\n", data_2d)
print("Total sum:", np.sum(data_2d))
print("Column sums (axis=0):", np.sum(data_2d, axis=0))
print("Row sums (axis=1):", np.sum(data_2d, axis=1))
print("Mean of all:", np.mean(data_2d))
print("Std dev:", np.std(data_2d))
print("Percentile (50th / median):", np.percentile(data_2d, 50))


### Axis Parameter

The `axis` parameter controls **which dimension** the operation applies to:

- `axis=0` — operate **down rows** (vertically, column-wise)
- `axis=1` — operate **across columns** (horizontally, row-wise)
- No axis — operate on **all elements** (flattened)

```python
matrix = np.array([[1, 2], [3, 4]])
np.sum(matrix)        # 10  (total)
np.sum(matrix, 0)     # [4, 6]  (column sums)
np.sum(matrix, 1)     # [3, 7]  (row sums)
```


## Statistical Functions

NumPy provides fast, vectorized statistical operations:

| Function | Description |
|----------|-------------|
| `np.mean(a)` | Arithmetic mean |
| `np.median(a)` | Median value |
| `np.std(a)` | Standard deviation |
| `np.var(a)` | Variance |
| `np.min(a)` / `np.max(a)` | Minimum / Maximum |
| `np.percentile(a, q)` | Any percentile |
| `np.sum(a)` / `np.prod(a)` | Sum / Product |

All accept an `axis` parameter to operate along a specific dimension.


In [ ]:
data = np.array([12, 45, 23, 67, 34, 89, 15, 42])
print(f"Mean:   {np.mean(data):.2f}")
print(f"Median: {np.median(data):.2f}")
print(f"Std:    {np.std(data):.2f}")
print(f"Min:    {np.min(data)}")
print(f"Max:    {np.max(data)}")
print(f"Sum:    {np.sum(data)}")

# Axis example with 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Row sums:", np.sum(matrix, axis=1))    # [ 6 15]
print("Col sums:", np.sum(matrix, axis=0))    # [5 7 9]


In [14]:
# Display the original array
arr

array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]])

In [10]:
# Reshape 120 elements into shape (2, 3, 4, 5)
arr = np.array(range(1,121)).reshape(2,3,4,5)

In [13]:
# & means 'and', | means 'or' for boolean arrays
# Multiple conditions with boolean operators


condition = [(arr%2 == 0),(arr %2 != 0)]
Even_odds = ["Even","Odd"]
EvenOddArray = np.select(condition,grade,default="UnKnown")
print(EvenOddArray)

[[[['Odd' 'Even' 'Odd' 'Even' 'Odd']
   ['Even' 'Odd' 'Even' 'Odd' 'Even']
   ['Odd' 'Even' 'Odd' 'Even' 'Odd']
   ['Even' 'Odd' 'Even' 'Odd' 'Even']]

  [['Odd' 'Even' 'Odd' 'Even' 'Odd']
   ['Even' 'Odd' 'Even' 'Odd' 'Even']
   ['Odd' 'Even' 'Odd' 'Even' 'Odd']
   ['Even' 'Odd' 'Even' 'Odd' 'Even']]

  [['Odd' 'Even' 'Odd' 'Even' 'Odd']
   ['Even' 'Odd' 'Even' 'Odd' 'Even']
   ['Odd' 'Even' 'Odd' 'Even' 'Odd']
   ['Even' 'Odd' 'Even' 'Odd' 'Even']]]


 [[['Odd' 'Even' 'Odd' 'Even' 'Odd']
   ['Even' 'Odd' 'Even' 'Odd' 'Even']
   ['Odd' 'Even' 'Odd' 'Even' 'Odd']
   ['Even' 'Odd' 'Even' 'Odd' 'Even']]

  [['Odd' 'Even' 'Odd' 'Even' 'Odd']
   ['Even' 'Odd' 'Even' 'Odd' 'Even']
   ['Odd' 'Even' 'Odd' 'Even' 'Odd']
   ['Even' 'Odd' 'Even' 'Odd' 'Even']]

  [['Odd' 'Even' 'Odd' 'Even' 'Odd']
   ['Even' 'Odd' 'Even' 'Odd' 'Even']
   ['Odd' 'Even' 'Odd' 'Even' 'Odd']
   ['Even' 'Odd' 'Even' 'Odd' 'Even']]]]


## Random Module

`np.random` generates random numbers for simulations and testing:
- `np.random.randint(low, high, size)` — random integers
- `np.random.rand(d0, d1, ...)` — uniform [0, 1)
- `np.random.randn(d0, d1, ...)` — standard normal distribution


In [ ]:
# randint generates random integers in [low, high)
# Seed ensures reproducible random numbers
# Different random distributions
np.random.seed(123)

# Uniform distribution [0, 1)
uniform = np.random.rand(1000)
print("Uniform mean:", uniform.mean(), "(expected ~0.5)")

# Standard normal distribution (mean=0, std=1)
normal = np.random.randn(1000)
print("Normal mean:", normal.mean(), "std:", normal.std())

# Random integers
rand_ints = np.random.randint(1, 7, 10)  # like rolling a die 10 times
print("Die rolls:", rand_ints)

# Normal distribution with custom parameters
custom_normal = np.random.normal(loc=100, scale=15, size=5)
print("Normal(100, 15):", custom_normal)


## Random Module

`np.random` provides many random sampling functions:

| Function | Description |
|----------|-------------|
| `np.random.rand(d0, d1)` | Uniform [0, 1) |
| `np.random.randn(d0, d1)` | Standard normal (mean=0, std=1) |
| `np.random.randint(low, high, size)` | Random integers |
| `np.random.normal(mean, std, size)` | Normal distribution |
| `np.random.uniform(low, high, size)` | Uniform distribution |
| `np.random.seed(n)` | Set seed for reproducible results |

Use `seed()` for **reproducibility** — same seed = same random numbers.


In [ ]:
np.random.seed(42)  # for reproducible results

rand_ints = np.random.randint(1, 101, 10)
print("Random integers:", rand_ints)

rand_3x3 = np.random.rand(3, 3)
print("Random 3x3 matrix:\n", rand_3x3)

normal_data = np.random.randn(1000)
print(f"Mean: {np.mean(normal_data):.4f}, Std: {np.std(normal_data):.4f}")
